-- vi: ft=lua
project = "bliss 0.0.0"
title = "bliss 0.0.0 reference"
description = "kiss in Lua"

not_luadoc = true
output = "doc"
sort = true
readme = "README.md"
format = "markdown"

file = {
	"main.lua",
	"bliss/archive.lua",
	"bliss/b3sum.c",
	"bliss/build.lua",
	"bliss/checksum.lua",
	"bliss/download.lua",
	"bliss/init.lua",
	"bliss/install.lua",
	"bliss/list.lua",
	"bliss/pkg.lua",
	"bliss/search.lua",
	"bliss/tsort.lua",
	"bliss/update.lua",
	"bliss/utils.lua",
}
